# Generated by Django 5.0.6 on 2024-11-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_id', models.CharField(blank=True, max_length=255, null=True)),
                ('analysis_results', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
